conditions:
  clear:
    - Sunny
    - Clear
  partly_cloudy:
    - Partly cloudy
  cloudy:
    - Cloudy
  overcast:
    - Overcast
  patchy_rain:
    - Patchy rain possible
    - Moderate rain at times
    - Patchy light rain
    - Light drizzle
    - Patchy light drizzle
    - Patchy snow possible
    - Patchy freezing drizzle possible
    - Patchy sleet possible
  patchy_rain_thunder:
    - Patchy light snow with thunder
    - Patchy light rain with thunder
    - Thundery outbreaks possible
  light_shower:
    - Light showers of ice pellets
    - Light snow showers
    - Light sleet showers
    - Light rain shower
    - Light snow
    - Patchy light snow
    - Light sleet
    - Blowing snow
    - Freezing drizzle
    - Light rain
    - Moderate rain
    - Heavy rain at times
    - Light freezing rain
  moderate_shower:
    - Moderate or heavy snow with thunder
    - Moderate or heavy rain with thunder
    - Torrential rain shower
    - Heavy snow
    - Blizzard
    - Heavy rain
    - Moderate or heavy showers of ice pellets
    - Moderate or heavy snow showers
    - Moderate or heavy sleet showers
    - Moderate or heavy rain shower
    - Ice pellets
    - Patchy heavy snow
    - Heavy freezing drizzle
    - Moderate snow
    - Patchy moderate snow
    - Moderate or heavy sleet
    - Heavy freezing drizzle
    - Moderate or heavy freezing rain
  fog:
    - Mist
    - Fog
    - Freezing fog

presets:
  clear:
    - Preset1
    - Preset2
    - Preset3
    - Preset4
    - Preset8
  partly_cloudy:
    - Preset5
    - Preset6
    - Preset7
    - Preset9
    - Preset10
    - Preset11
    - Preset12
  cloudy:
    - Preset13
    - Preset14
    - Preset15
    - Preset16
    - Preset17
    - Preset18
    - Preset19
    - Preset20
  overcast:
    - Preset21
    - Preset22
    - Preset23
    - Preset24
    - Preset25
    - Preset26
    - Preset27
  patchy_rain:
    - RainyPreset1
    - RainyPreset2
    - RainyPreset3
  patchy_rain_thunder:
    - RainyPreset1
    - RainyPreset2
    - RainyPreset3
  light_shower:
    - RainyPreset1
    - RainyPreset2
    - RainyPreset3
  moderate_shower:
    - RainyPreset1
    - RainyPreset2
    - RainyPreset3
  fog:
    - Preset0

icons:
  "clear": "//cdn.weatherapi.com/weather/64x64/night/113.png"
  "partly_cloudy": "//cdn.weatherapi.com/weather/64x64/night/116.png"
  "overcast": "//cdn.weatherapi.com/weather/64x64/day/122.png"
  "fog": "//cdn.weatherapi.com/weather/64x64/day/143.png"
  "light_shower": "//cdn.weatherapi.com/weather/64x64/day/317.png"
  "patchy_rain": "//cdn.weatherapi.com/weather/64x64/day/176.png"
  "moderate_shower": "//cdn.weatherapi.com/weather/64x64/day/356.png"
  "cloudy": "//cdn.weatherapi.com/weather/64x64/day/119.png"
  "patchy_rain_thunder": "//cdn.weatherapi.com/weather/64x64/day/386.png"
