BackendToDisplayName:
  FA-18C_hornet: FA-18C
  S-3B Tanker: S-3
  M-2000C: M-2000C
  F-16C_50: F-16
  F-16C bl.52d: F-16
  F-14A-135-GR: F-14
  F-4E: F-4
  F-14B: F-14
  AV8BNA: AV8BNA
  MiG-29S: MIG-29
  MiG-29A: MIG-29
  MiG-23MLD: MIG-23
  Su-33: Su-27
  F-5E-3: F-5
  MiG-21Bis: MIG-21
  Su-25T: Su-25
  Su-24M: Su-24
  E-2C: E-2
  E-2D: E-2
  E-3A: E-3
  F-15C: F-15
  A-10C_2: A-10
  A-10C: A-10
  KC135MPRS: KC-135MPRS
  AJS37: VIGGEN
  SA342Mistral: helicopter1
  SA342L: helicopter1
  SA342M: helicopter1
  UH-1H: UH-1
  Mi-8MT: Mi-8
  SH-60B: UH-60
  UH-60A: UH-60
  KC130: KC-130
  IL-76MD: IL-76
  An-26B: AN-26
  Tornado IDS: TORNADO
  RQ-1A Predator: RQ-1 Predator
  MQ-9 Reaper: MQ-9 Reaper
  Everyone: Everyone


CountryAliases:
  USSR: Russia
  CJTF Red: Russia
  CJTF Blue: USA
  USAF Aggressors: USA

PlaneToColor:
  Everyone: black
  Hornet: blue
  Viper: green
  Tomcat: red
  Harrier: orange
  Mirage: purple

# get icons for waypoints in https://getbootstrap.com/docs/3.3/components/
WayPointOptionToIcon:
  Anchor: anchor
  Route: play
  IP: sign-in
  Target: crosshairs
  FAC: eye
  SAM: exclamation-circle
  Home Base: home
  Tanker: battery-quarter
  Contested Area: fort-awesome
  Bullseye: bullseye
  Airport: fighter-jet
