DisplayToBackendName:
  Hornet: FA-18C_hornet
  Mirage: M-2000C
  Viper: F-16C_50
  Tomcat: F-14
  Harrier: AV8BNA
  Everyone: Everyone

PlaneToColor:
  Everyone: black
  Hornet: blue
  Viper: green
  Tomcat: red
  Harrier: orange
  Mirage: purple

# get icons for waypoints in https://getbootstrap.com/docs/3.3/components/
WayPointOptionToIcon:
  Anchor: anchor
  Route: play
  IP: sign-in
  Target: crosshairs
  FAC: eye
  SAM: exclamation-circle
  Home Base: home
  Tanker: battery-quarter
  Contested Area: fort-awesome
  Bullseye: bullseye
  Airport: fighter-jet
